[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "khmer_nlp_toolkits"
version = "0.1.0"
description = "Khmer NLP toolkits"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    regex==2024.11.6
    jsonlines==4.0.0
    ftfy==6.2.3
    tqdm==4.67.1
    dotenv==0.9.9
]

[tool.setuptools]
packages = { find = { } }
include-package-data = true

[tool.setuptools.package-data]
khmer_nlp_toolkits = ["utils/segment/model/*.bin"]
